// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndslginpmyploiuhktcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kc2xnaW5wbXlwbG9pdWhrdGNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5ODk5MDksImV4cCI6MjA1NjU2NTkwOX0.2dlw7FxVrfTSAsmuFNJe0pDnGki_sdQetemxUu5WNKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);