// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cctqwyhoryahdauqcetf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjdHF3eWhvcnlhaGRhdXFjZXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMTEyNDMsImV4cCI6MjA2Mjg4NzI0M30.QjTU2G8T2b7S9CgeG79uP-892C1h3Rj1McvzJIGoS4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);